// <auto-generated />
using System;
using GrandCircusLmsExample.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrandCircusLmsExample.DAL.Migrations
{
    [DbContext(typeof(GrandCircusLmsExampleContext))]
    [Migration("20200407022202_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrandCircusLmsExample.DAL.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Credits");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<int>("LocationId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("GrandCircusLmsExample.DAL.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Grade");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<int>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("GrandCircusLmsExample.DAL.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("GCIdentificationNumbe");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<string>("OfficeNumber");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("GrandCircusLmsExample.DAL.Models.InstructorCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId");

                    b.Property<int>("InstructorId");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorCourse");
                });

            modelBuilder.Entity("GrandCircusLmsExample.DAL.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GrandCircusLmsExample.DAL.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("DeclaredMajor");

                    b.Property<string>("FirstName");

                    b.Property<string>("GCIdentificationNumbe");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2020, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateTime(1995, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeclaredMajor = "Computer Science",
                            FirstName = "Jake",
                            GCIdentificationNumbe = "12001",
                            LastName = "Collins",
                            LastUpdatedDate = new DateTime(2020, 4, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2020, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateTime(1994, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeclaredMajor = "Computer Science",
                            FirstName = "Austin",
                            GCIdentificationNumbe = "12002",
                            LastName = "Powel",
                            LastUpdatedDate = new DateTime(2020, 4, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2020, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateTime(1998, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeclaredMajor = "Computer Science",
                            FirstName = "Dylan",
                            GCIdentificationNumbe = "12003",
                            LastName = "Rule",
                            LastUpdatedDate = new DateTime(2020, 4, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2020, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            DateOfBirth = new DateTime(1997, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeclaredMajor = "Computer Science",
                            FirstName = "Andrew",
                            GCIdentificationNumbe = "12004",
                            LastName = "Waltman",
                            LastUpdatedDate = new DateTime(2020, 4, 6, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("GrandCircusLmsExample.DAL.Models.Course", b =>
                {
                    b.HasOne("GrandCircusLmsExample.DAL.Models.Location", "Location")
                        .WithMany("Courses")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GrandCircusLmsExample.DAL.Models.Enrollment", b =>
                {
                    b.HasOne("GrandCircusLmsExample.DAL.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GrandCircusLmsExample.DAL.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GrandCircusLmsExample.DAL.Models.InstructorCourse", b =>
                {
                    b.HasOne("GrandCircusLmsExample.DAL.Models.Course", "Course")
                        .WithMany("InstructorCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GrandCircusLmsExample.DAL.Models.Instructor", "Instructor")
                        .WithMany("InstructorCourses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
